#! /bin/sh
# 
#                ,-,--.     _ __           ,-.-.        ___   
#     _..---.  ,-.'-  _\ .-`.' ,`.,-..-.-./  \==\.-._ .'=.'\  
#   .' .'.-. \/==/_ ,_.'/==/, -   \, \=/\=|- |==/==/ \|==|  | 
#  /==/- '=' /\==\  \  |==| _ .=. |- |/ |/ , /==/==|,|  / - | 
#  |==|-,   '  \==\ -\ |==| , '=',|\, ,     _|==|==|  \/  , | 
#  |==|  .=. \ _\==\ ,\|==|-  '..' | -  -  , |==|==|- ,   _ | 
#  /==/- '=' ,/==/\/ _ |==|,  |     \  ,  - /==/|==| _ /\   | 
# |==|   -   /\==\ - , /==/ - |     |-  /\ /==/ /==/  / / , / 
# `-._`.___,'  `--`---'`--`---'     `--`  `--`  `--`./  `--`  
# 
# 
##################################################################


sxhkd &

bspc monitor DP-0 -d 1 2 3 4 5
bspc monitor DP-2 -d 6 7 8 9 10


#bspc monitor DP3 -d     
#bspc monitor eDP1 -d     

bspc config border_width         0
bspc config window_gap           20
bspc config focus_follows_pointer true
bspc config split_ratio          0.58
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color0"
bspc config active_border_color "$color0"
bspc config focused_border_color "$color5"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

#bspc rule -a spotify desktop='^3'
#bspc rule -a code-oss desktop='^4'
#bspc rule -a gravit-designer desktop=^5
bspc rule -a dolphin state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Nemo state=floating
bspc rule -a file-roller state=floating
bspc rule -a Galculator state=floating
bspc rule -a Zoom state=floating

/home/justin/Documents/Scripts/home.sh
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/home/justin/Documents/Scripts/wally.sh
/home/justin/.config/polybar/launch.sh
picom --config ~/.config/picom/picom.conf -b
